### ISSUE TITLE
Container Error

### ISSUE THREAD

**Issue by alienatedsec** [NosIreland/solismon3#3]
Hi @NosIreland 

First of all - thanks for the effort - I am trying to set something locally using the QNAP NAS container.
I am experiencing the same issue as this one https://github.com/NosIreland/solismod/issues/1

```
File "/solismon3/./main.py", line 2, in <module>
import config.config as config
ModuleNotFoundError: No module named 'config'
```
Any chance of finding how to fix this in the docker container?

**Comment by NosIreland** [comment]
It cannot start as it either missing or cannot access configuration file config.py 
Can you post your docker-compose file?

**Comment by alienatedsec** [comment]
I have now managed to start it, but it doesn't publish to the broker even though it's connected and no errors are displayed.

**Comment by NosIreland** [comment]
paste your config.py file, remove serial number

**Comment by alienatedsec** [comment]
It works on my Debian rig but not in Container. Debugging seems to be silent after 
`2022-10-11 16:29:00 INFO     Publishing MQTT`

config.py
```
INVERTER_SERIAL = ************ # WiFi stick serial number
INVERTER_IP = "192.168.******" # IP address of inverter
INVERTER_PORT = 8899          # Port number
MQTT_SERVER = "192.168.******" # IP address of MQTT server
MQTT_PORT = 1883              # Port number of MQTT server
MQTT_TOPIC = "solis/METRICS"  # MQTT topic to use
MQTT_USER = "mqtt"            # MQTT auth user
MQTT_PASS = "**********"   # MQTT auth password
CHECK_INTERVAL = 30           # How often to check(seconds), only applies when 'PROMETHEUS = False' otherwise uses Prometheus scrape interval
MQTT_KEEPALIVE = 60           # MQTT keepalive
PROMETHEUS = False            # Enable Prometheus exporter
PROMETHEUS_PORT = 18000       # Port to use for Prometheus exporter
MODIFIED_METRICS = True       # Enable modified metrics
DEBUG = True                 # Enable debugging, helpfull to diagnose problems

```

I reckon there is no authentication in the container version `main.py`

**Comment by NosIreland** [comment]
Yes, mqtt authentication PR was merged today. I have just pushed new image with authentication.
Delete the image that you have at the moment `docker rmi nosireland/solismon3:latest` and run docker-compose again. It will pull the latest with authentication.

**Comment by alienatedsec** [comment]
@NosIreland Still the same - nothing is published

Is there a way to confirm the latest was pulled from the docker?

**Comment by alienatedsec** [comment]
![image](https://user-images.githubusercontent.com/73167064/195159737-f7fd6342-03f2-45b0-a12c-3478455b1010.png)

**Comment by alienatedsec** [comment]
Finally - Thanks for the docker push

I had to delete all images and redownload from the docker hub.
BTW QNAP Container Station is not the greatest.
